export const ADJECTIVES = [
  'able', 'active', 'adapt', 'adept', 'alert', 'alive', 'amber', 'ample', 'apt', 'art',
  'avid', 'aware', 'balanced', 'beaming', 'big', 'bold', 'brave', 'bright', 'brisk', 'broad',
  'calm', 'candid', 'capable', 'careful', 'casual', 'certain', 'charming', 'cheerful', 'chief', 'clean',
  'clear', 'clever', 'close', 'cool', 'cozy', 'crisp', 'curious', 'cute', 'dainty', 'daring',
  'dear', 'deep', 'delicate', 'direct', 'diverse', 'divine', 'eager', 'earnest', 'easy', 'elite',
  'equal', 'exact', 'expert', 'fair', 'famed', 'fast', 'fierce', 'fine', 'firm', 'first',
  'fit', 'flash', 'fleet', 'fluid', 'fond', 'frank', 'free', 'fresh', 'full', 'fun',
  'funny', 'fuzzy', 'game', 'gay', 'gentle', 'genuine', 'gifted', 'glad', 'gold', 'good',
  'grand', 'grateful', 'great', 'happy', 'hardy', 'healthy', 'hearty', 'helpful', 'high', 'holy',
  'honest', 'humble', 'ideal', 'idle', 'immense', 'intent', 'iron', 'jolly', 'joyful', 'just',
  'keen', 'kind', 'known', 'large', 'last', 'late', 'leading', 'lean', 'level', 'light',
  'likely', 'limber', 'little', 'live', 'lively', 'local', 'lofty', 'lone', 'long', 'loose',
  'loud', 'loved', 'lovely', 'loving', 'loyal', 'lucky', 'lush', 'magic', 'main', 'major',
  'many', 'massive', 'mature', 'max', 'meek', 'mellow', 'merry', 'mighty', 'mild', 'mini',
  'modern', 'modest', 'moral', 'mute', 'mutual', 'mystic', 'native', 'natural', 'neat', 'needed',
  'new', 'next', 'nice', 'noble', 'normal', 'noted', 'novel', 'null', 'oaken', 'obedient',
  'objective', 'open', 'optimal', 'orange', 'orderly', 'organic', 'original', 'ornate', 'other', 'outdoor',
  'oval', 'patient', 'peaceful', 'perfect', 'petite', 'pink', 'plain', 'plump', 'polite', 'poor',
  'popular', 'posh', 'potent', 'pretty', 'prime', 'pro', 'prompt', 'proper', 'proud', 'proud',
  'puffy', 'pure', 'purple', 'quick', 'quiet', 'rare', 'ready', 'real', 'red', 'rich',
  'right', 'rigid', 'ripe', 'robust', 'rosy', 'rough', 'round', 'royal', 'ruby', 'rude',
  'rustic', 'sacred', 'safe', 'sage', 'same', 'savvy', 'scarce', 'secure', 'sharp', 'shiny',
  'short', 'shy', 'silent', 'silky', 'simple', 'sincere', 'sleek', 'slender', 'slight', 'slim',
  'slow', 'small', 'smart', 'smooth', 'snug', 'soft', 'solid', 'soon', 'sound', 'sour',
  'spare', 'special', 'speedy', 'spry', 'square', 'stable', 'stale', 'stark', 'steady', 'steep',
  'stern', 'still', 'stoic', 'strong', 'sturdy', 'subtle', 'sudden', 'sugar', 'sunny', 'super',
  'superb', 'sure', 'sweet', 'swift', 'tall', 'tame', 'tart', 'taut', 'teal', 'tender',
  'tense', 'tight', 'tiny', 'tired', 'top', 'total', 'tough', 'trim', 'true', 'twin',
  'uber', 'ultra', 'unique', 'united', 'upbeat', 'upper', 'upright', 'urban', 'used', 'usual',
  'vague', 'vain', 'valid', 'vast', 'vegan', 'vivid', 'vocal', 'void', 'warm', 'weak',
  'wealthy', 'weary', 'welcome', 'well', 'wet', 'white', 'whole', 'wide', 'wild', 'willing',
  'wily', 'wise', 'witty', 'worthy', 'young', 'zany', 'zesty',
];
